force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>need to store position related data</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Bypass_Validation_Skill_Required_Field__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Skill_Required_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation_Skill Required Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Minimum_Experience_Required__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Experience_Required__c</fullName>
    <label>Minimum Experience Required</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DMLUpsert.cls
public class DMLUpsert {
    
    public static void UpsertPosition()
    {
        List<Position__c> poslist=new List<Position__c>();
        Position__c pos1=new Position__c();
        
        pos1.Id='a00NS000018CDKYYA4';
        pos1.Name='Happy Anushka chaudhari';
        poslist.add(pos1);
         
        Position__c pos2=new Position__c();
        pos2.Name='Prabhav';
        pos2.Minimum_Experience_Required__c=7;
        pos2.Bypass_Validation_Skill_Required_Field__c=True;
        poslist.add(pos2);
        
        Upsert poslist;
        
        
    }

}