force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>need to store position related data</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Bypass_Validation_Skill_Required_Field__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Skill_Required_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation_Skill Required Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Minimum_Experience_Required__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Experience_Required__c</fullName>
    <label>Minimum Experience Required</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DMLInsertion.cls
public class DMLInsertion {
    
    
    Public static Void InsertAccount()
    {
       
        List<Account> acclist=new  List<Account>();
        For (Integer i=0;i<=10;i++)
        {
             Account acc=new Account();
            acc.Name='Account'+i;
            acc.AccountNumber='123456789'+i;
            acclist.add(acc);
        }
        Insert acclist;
    }
    
    Public static void Insertposition()
    {
        list<Position__c> poslist=new  list<Position__c>();
        
        Position__c pos=new Position__c();
        pos.Name='Prabhav';
        pos.Minimum_Experience_Required__c=7;
        pos.Bypass_Validation_Skill_Required_Field__c=True;
        Insert pos;
        
        
    }
   


}