force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>need to store position related data</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Bypass_Validation_Skill_Required_Field__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Skill_Required_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation_Skill Required Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Max_Pay__c.field-meta.xml
<CustomField>
    <fullName>Max_Pay__c</fullName>
    <label>Max Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Min_Pay__c.field-meta.xml
<CustomField>
    <fullName>Min_Pay__c</fullName>
    <label>Min Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open-Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Failed</fullName>
            </value>
            <value>
                <fullName>Closed - Not Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type Of Employee</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DMLUpdate.cls
public class DMLUpdate {
    
    Public Static void updateAccount()
    {
        List<Account> acclist = [SELECT Id, Name FROM Account WHERE CreatedDate = TODAY];
        for(Integer i=0;i<=10;i++)
        {
           acclist[i].Name='Accenture'+i;
            
        }
        Update acclist;
    }
    
    Public Static void UpdatePosition()
    {
        Position__c pos=new Position__c();
        pos.Id='a00NS000018TvHAYA0';
        pos.Name='Prabhav 1000';
        pos.Bypass_Validation_Skill_Required_Field__c=True;
        pos.Min_Pay__c=1000;
        pos.Max_Pay__c=50000;
        pos.Type__c='Full Time';
        pos.Status__c='New Position';
        Update pos;
     }

}