force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>need to store position related data</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open-Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Failed</fullName>
            </value>
            <value>
                <fullName>Closed - Not Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BeforeUpdate2HandlerPosition.cls
public class BeforeUpdate2HandlerPosition {
    
    public static void updateOperation(List<Position__c>poslist)
    {
        for(Position__c pos:poslist)
        {
            if(pos.status__c == 'Open-Approved')
            {
                pos.Open_Date__c = Date.today();
            }
            
            if(pos.status__c == 'Closed - Failed' || pos.status__c == 'Closed - Not Approved' || pos.status__c == 'Closed - Cancel' )
            {
                pos.Close_Date__c = Date.today();
            }


        }
    }

}